SELECT null as PROCEDURE_CAT,
    null as PROCEDURE_SCHEM,
    null as PROCEDURE_NAME,
    null as COLUMN_NAME,
    null as COLUMN_TYPE,
    null as DATA_TYPE,
    null as TYPE_NAME,
    null as PRECISION,
    null as LENGTH,
    null as SCALE,
    null as RADIX,
    null as NULLABLE,
    null as REMARKS,
    null as COLUMN_DEF,
    null as SQL_DATA_TYPE,
    null as SQL_DATETIME_SUB,
    null as CHAR_OCTET_LENGTH,
    null as ORDINAL_POSITION,
    null as IS_NULLABLE,
    null as SPECIFIC_NAME
    LIMIT 0
