SELECT null AS FUNCTION_CAT,
    null AS FUNCTION_SCHEM,
    FUNCTION_NAME,
    REMARKS,
    1 AS FUNCTION_TYPE,
    FUNCTION_NAME AS SPECIFIC_NAME
    FROM metadata_function
    WHERE FUNCTION_NAME LIKE ?
    ORDER BY FUNCTION_CAT, FUNCTION_SCHEM, FUNCTION_NAME, SPECIFIC_NAME
